# -*- coding: utf-8 -*-
"""Flames_Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oyFVwS3MELu59LtLhURgZDzIMZ8JB0mn
"""

# FLAMES Game

print("FLAMES Game")

# taking names from user
name1 = input("Enter first name: ")
name2 = input("Enter second name: ")

# converting to lowercase and removing spaces
name1 = name1.lower().replace(" ", "")
name2 = name2.lower().replace(" ", "")

# converting names into list
list1 = list(name1)
list2 = list(name2)

# removing common letters
for letter in list1[:]:   # using copy so no error while removing
    if letter in list2:
        list1.remove(letter)
        list2.remove(letter)

# counting remaining letters
count = len(list1) + len(list2)

# FLAMES letters
flames = ['F', 'L', 'A', 'M', 'E', 'S']

# running loop until one letter remains
while len(flames) > 1:
    split_index = (count % len(flames)) - 1

    if split_index >= 0:
        # splitting list into two parts
        right = flames[split_index + 1:]
        left = flames[:split_index]

        # joining parts
        flames = right + left
    else:
        flames = flames[:-1]

# getting final result
result = flames[0]

# mapping result to meaning
if result == 'F':
    result_text = "Friends"
elif result == 'L':
    result_text = "Love"
elif result == 'A':
    result_text = "Affection"
elif result == 'M':
    result_text = "Marriage"
elif result == 'E':
    result_text = "Enemies"
elif result == 'S':
    result_text = "Siblings"

# final output
print("Relationship is:", result_text)